<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kwaku Owusu-Tieku">
<meta name="dcterms.date" content="2026-07-20">

<title>Adult Income (1994 Census) — Exploratory Data Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-10daa034703793678e481cc8cee6d76f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a>
  <ul class="collapse">
  <li><a href="#source" id="toc-source" class="nav-link" data-scroll-target="#source">Source</a></li>
  <li><a href="#sample-representativeness" id="toc-sample-representativeness" class="nav-link" data-scroll-target="#sample-representativeness">Sample Representativeness</a></li>
  <li><a href="#reading-the-data" id="toc-reading-the-data" class="nav-link" data-scroll-target="#reading-the-data">Reading the Data</a></li>
  </ul></li>
  <li><a href="#data-quality-checks" id="toc-data-quality-checks" class="nav-link" data-scroll-target="#data-quality-checks">Data Quality Checks</a>
  <ul class="collapse">
  <li><a href="#record-count-verification" id="toc-record-count-verification" class="nav-link" data-scroll-target="#record-count-verification">Record Count Verification</a></li>
  <li><a href="#null-missing-value-check" id="toc-null-missing-value-check" class="nav-link" data-scroll-target="#null-missing-value-check">Null / Missing Value Check</a></li>
  <li><a href="#numeric-range-validation" id="toc-numeric-range-validation" class="nav-link" data-scroll-target="#numeric-range-validation">Numeric Range Validation</a></li>
  <li><a href="#categorical-level-inventory" id="toc-categorical-level-inventory" class="nav-link" data-scroll-target="#categorical-level-inventory">Categorical Level Inventory</a></li>
  <li><a href="#income-class-split" id="toc-income-class-split" class="nav-link" data-scroll-target="#income-class-split">Income Class Split</a></li>
  </ul></li>
  <li><a href="#data-visualization-and-exploration" id="toc-data-visualization-and-exploration" class="nav-link" data-scroll-target="#data-visualization-and-exploration">Data Visualization and Exploration</a>
  <ul class="collapse">
  <li><a href="#guiding-questions" id="toc-guiding-questions" class="nav-link" data-scroll-target="#guiding-questions">Guiding Questions</a></li>
  <li><a href="#distributions" id="toc-distributions" class="nav-link" data-scroll-target="#distributions">Distributions</a>
  <ul class="collapse">
  <li><a href="#numeric-variable-shapes" id="toc-numeric-variable-shapes" class="nav-link" data-scroll-target="#numeric-variable-shapes">Numeric variable shapes</a></li>
  <li><a href="#age-and-the-mid-career-earnings-band" id="toc-age-and-the-mid-career-earnings-band" class="nav-link" data-scroll-target="#age-and-the-mid-career-earnings-band">Age and the mid-career earnings band</a></li>
  </ul></li>
  <li><a href="#trends" id="toc-trends" class="nav-link" data-scroll-target="#trends">Trends</a>
  <ul class="collapse">
  <li><a href="#education-and-the-threshold-that-almost-matters" id="toc-education-and-the-threshold-that-almost-matters" class="nav-link" data-scroll-target="#education-and-the-threshold-that-almost-matters">Education and the threshold that almost matters</a></li>
  </ul></li>
  <li><a href="#anomalies-and-domain-specific-findings" id="toc-anomalies-and-domain-specific-findings" class="nav-link" data-scroll-target="#anomalies-and-domain-specific-findings">Anomalies and Domain-Specific Findings</a>
  <ul class="collapse">
  <li><a href="#the-gender-income-gap-and-what-it-actually-measures" id="toc-the-gender-income-gap-and-what-it-actually-measures" class="nav-link" data-scroll-target="#the-gender-income-gap-and-what-it-actually-measures">The gender income gap and what it actually measures</a></li>
  <li><a href="#occupation-a-structural-income-floor" id="toc-occupation-a-structural-income-floor" class="nav-link" data-scroll-target="#occupation-a-structural-income-floor">Occupation: a structural income floor</a></li>
  <li><a href="#capital-gains-investment-income-as-a-high-earner-signal" id="toc-capital-gains-investment-income-as-a-high-earner-signal" class="nav-link" data-scroll-target="#capital-gains-investment-income-as-a-high-earner-signal">Capital gains: investment income as a high-earner signal</a></li>
  <li><a href="#race-disparities-a-coarse-but-real-signal" id="toc-race-disparities-a-coarse-but-real-signal" class="nav-link" data-scroll-target="#race-disparities-a-coarse-but-real-signal">Race disparities: a coarse but real signal</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a>
  <ul class="collapse">
  <li><a href="#analysis-approach-next-phase" id="toc-analysis-approach-next-phase" class="nav-link" data-scroll-target="#analysis-approach-next-phase">Analysis Approach (Next Phase)</a></li>
  </ul></li>
  <li><a href="#technical-notes" id="toc-technical-notes" class="nav-link" data-scroll-target="#technical-notes">Technical Notes</a>
  <ul class="collapse">
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility">Reproducibility</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Adult Income (1994 Census) — Exploratory Data Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kwaku Owusu-Tieku </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 20, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>This dataset records 32,561 individuals drawn from the 1994 US Current Population Survey (CPS) by Barry Becker at UC Irvine. Each row describes a working-age adult’s demographic characteristics and whether their annual income exceeds $50,000. The dataset was published as a machine-learning benchmark in the UCI repository, where its original purpose was binary income classification.</p>
<p>This analysis treats it not as a benchmark but as a window into the US labor market in 1994 — who was earning above a threshold equivalent to roughly $100,000 in today’s dollars, and which structural factors (education, occupation, marital status, age) tracked most closely with that outcome. Three questions guide the analysis:</p>
<ol type="1">
<li>Where in the educational hierarchy does high income become the <em>majority</em> outcome, rather than the exception?</li>
<li>What does the widely-reported gender income gap actually look like once marital status is held constant?</li>
<li>What does the structure of capital gains in this sample reveal about who builds wealth through investment vs.&nbsp;wage income alone?</li>
</ol>
<p><strong>Domain brief note.</strong> This analysis was conducted for learning and skill demonstration purposes, without a specific downstream decision or audience constraint. The analysis proceeds on the analyst’s own judgment about what the data most clearly shows.</p>
</section>
<section id="the-data" class="level1">
<h1>The Data</h1>
<section id="source" class="level2">
<h2 class="anchored" data-anchor-id="source">Source</h2>
<p>The underlying data is the <strong>1994 Census Bureau Current Population Survey (CPS)</strong>, specifically the “adult” extract created by Barry Becker and Ronny Kohavi and deposited in the UCI Machine Learning Repository. The CPS is a monthly survey of roughly 60,000 US households conducted jointly by the Bureau of Labor Statistics and the Census Bureau; the 1994 extract targets the civilian noninstitutional population aged 16 and older.</p>
<p>Collection era: <strong>1994.</strong> $50,000 in 1994 dollars is equivalent to approximately <strong>$105,800 in 2024 dollars</strong> (BLS CPI-U: annual index 148.2 in 1994 → 313.7 in 2024). The threshold was not modest: it sat approximately 60% above the 1994 male median full-time/year-round earnings of $31,609 (Census P60-189), and was more than double the female median of $23,261. The SSA national average wage for all covered workers in 1994 was $23,754 — less than half the threshold. In the actual 1994 labor force, $50K individual income placed a worker in roughly the top 20–25% of earners. Any claim made from this data should be read in that era context; wage distributions, educational attainment, and labor force participation have all shifted substantially in the intervening 30 years.</p>
<p>The dataset does not include a <code>year</code> column — it is a cross-sectional extract, not a longitudinal record.</p>
</section>
<section id="sample-representativeness" class="level2">
<h2 class="anchored" data-anchor-id="sample-representativeness">Sample Representativeness</h2>
<p>The dataset’s demographic composition compared against the 1994 civilian labor force (BLS EcoPro Table 1):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group</th>
<th>Dataset</th>
<th>BLS 1994</th>
<th>Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Female</td>
<td>33.1%</td>
<td>45.9%</td>
<td>−12.8 pts</td>
</tr>
<tr class="even">
<td>White</td>
<td>85.4%</td>
<td>84.8%</td>
<td>+0.6 pts</td>
</tr>
<tr class="odd">
<td>Black</td>
<td>9.6%</td>
<td>11.1%</td>
<td>−1.5 pts</td>
</tr>
<tr class="even">
<td>Asian(-Pac-Islander)</td>
<td>3.2%</td>
<td>4.2%</td>
<td>−1.0 pts</td>
</tr>
<tr class="odd">
<td>Bachelor’s or higher</td>
<td>24.8%</td>
<td>~24–25%</td>
<td>~0</td>
</tr>
</tbody>
</table>
<p><strong>White racial composition matches the 1994 labor force almost exactly.</strong> Educational composition also aligns. However, <strong>the dataset substantially underrepresents women</strong> — 33.1% female vs.&nbsp;45.9% in the actual labor force, a 12.8-point gap. This is consistent with the CPS sampling frame excluding non-labor-force participants and potentially reflecting a 1994 extraction methodology that skewed male. Black and Asian representation are mildly underrepresented by 1–1.5 points.</p>
<p>The unweighted analyses throughout this report are based on a sample that underrepresents women by roughly one-eighth. The fnlwgt sampling weights would correct for this in a weighted analysis; using unweighted results for gender comparisons means the male perspective is weighted approximately 2:1 over the female perspective relative to the actual 1994 labor force. This does not invalidate the within-group findings (e.g., the married-female vs.&nbsp;married-male comparison) but it does affect any aggregate female income statistics.</p>
</section>
<section id="reading-the-data" class="level2">
<h2 class="anchored" data-anchor-id="reading-the-data">Reading the Data</h2>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">"../data/processed/adult_clean.parquet"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>Column dictionary</strong> (15 columns, no header row in the source file — names applied from <code>adult.names</code>):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Column</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>age</td>
<td>numeric</td>
<td>Age in years; possible top-code at 90</td>
</tr>
<tr class="even">
<td>workclass</td>
<td>categorical</td>
<td>Employment sector (Private, Federal-gov, Self-emp-inc, etc.)</td>
</tr>
<tr class="odd">
<td>fnlwgt</td>
<td>numeric</td>
<td>CPS sampling weight — how many US adults this row represents</td>
</tr>
<tr class="even">
<td>education</td>
<td>ordered categorical</td>
<td>Highest degree attained (Preschool → Doctorate)</td>
</tr>
<tr class="odd">
<td>education_num</td>
<td>numeric</td>
<td>Numeric encoding of education (1=Preschool, 16=Doctorate)</td>
</tr>
<tr class="even">
<td>marital_status</td>
<td>categorical</td>
<td>7 categories including three married variants</td>
</tr>
<tr class="odd">
<td>occupation</td>
<td>categorical</td>
<td>Job type (14 named + missing)</td>
</tr>
<tr class="even">
<td>relationship</td>
<td>categorical</td>
<td>Household relationship role (Husband, Wife, etc.)</td>
</tr>
<tr class="odd">
<td>race</td>
<td>categorical</td>
<td>5 categories</td>
</tr>
<tr class="even">
<td>sex</td>
<td>categorical</td>
<td>Male / Female</td>
</tr>
<tr class="odd">
<td>capital_gain</td>
<td>numeric</td>
<td>Annual investment income gain; top-coded at $99,999</td>
</tr>
<tr class="even">
<td>capital_loss</td>
<td>numeric</td>
<td>Annual investment income loss</td>
</tr>
<tr class="odd">
<td>hours_per_week</td>
<td>numeric</td>
<td>Reported weekly work hours; top-coded at 99</td>
</tr>
<tr class="even">
<td>native_country</td>
<td>categorical</td>
<td>Country of birth; 41 named + missing</td>
</tr>
<tr class="odd">
<td>income</td>
<td>binary</td>
<td>≤$50K or &gt;$50K</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="data-quality-checks" class="level1">
<h1>Data Quality Checks</h1>
<section id="record-count-verification" class="level2">
<h2 class="anchored" data-anchor-id="record-count-verification">Record Count Verification</h2>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>tbl_rc <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"../data/processed/tbl_record_count.rds"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(tbl_rc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: right;">Expected</th>
<th style="text-align: right;">Actual</th>
<th style="text-align: left;">Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rows</td>
<td style="text-align: right;">32561</td>
<td style="text-align: right;">32561</td>
<td style="text-align: left;">Matches documented train-set size</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>32,561 rows, exactly matching the documented UCI training-set size. No discrepancy.</p>
</section>
<section id="null-missing-value-check" class="level2">
<h2 class="anchored" data-anchor-id="null-missing-value-check">Null / Missing Value Check</h2>
<p>The raw file encodes all missing values as the string <code>"?"</code> rather than true <code>NA</code> — a disguised-null convention. Three columns are affected:</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>tbl_miss <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"../data/processed/tbl_missing.rds"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(tbl_miss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 68%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Column</th>
<th style="text-align: right;">? count</th>
<th style="text-align: right;">% of rows</th>
<th style="text-align: left;">Handling</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">workclass</td>
<td style="text-align: right;">1836</td>
<td style="text-align: right;">5.6</td>
<td style="text-align: left;">Replaced with NA; kept in dataset; sensitivity noted</td>
</tr>
<tr class="even">
<td style="text-align: left;">occupation</td>
<td style="text-align: right;">1843</td>
<td style="text-align: right;">5.7</td>
<td style="text-align: left;">Replaced with NA; structurally co-missing with workclass for 1,836 rows</td>
</tr>
<tr class="odd">
<td style="text-align: left;">native_country</td>
<td style="text-align: right;">583</td>
<td style="text-align: right;">1.8</td>
<td style="text-align: left;">Replaced with NA; kept in dataset; independent missingness pattern</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>workclass and occupation are co-missing for 1,836 rows exactly.</strong> Zero rows have missing workclass without also having missing occupation. This is structural — the same respondents who declined to specify employment sector consistently also left occupation blank. Among these 1,836 rows, only 10.4% earn &gt;$50K, compared to 24.1% in the full dataset. Dropping missing rows would mildly oversample high-income individuals. In this EDA, missing rows are retained with <code>NA</code> values and excluded from per-group proportions where noted.</p>
<p><strong>native_country missingness is independent.</strong> Only 27 of the 583 missing native_country rows also have missing workclass — different respondents, different pattern, likely different non-response reason.</p>
</section>
<section id="numeric-range-validation" class="level2">
<h2 class="anchored" data-anchor-id="numeric-range-validation">Numeric Range Validation</h2>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>tbl_ranges <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"../data/processed/tbl_ranges.rds"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(tbl_ranges)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 13%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Column</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Max</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Median</th>
<th style="text-align: left;">Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">38.6</td>
<td style="text-align: right;">37</td>
<td style="text-align: left;">Age 90 appears 43 times — possible Census top-code; plausible range</td>
</tr>
<tr class="even">
<td style="text-align: left;">fnlwgt</td>
<td style="text-align: right;">12285</td>
<td style="text-align: right;">1484705</td>
<td style="text-align: right;">189778.0</td>
<td style="text-align: right;">178356</td>
<td style="text-align: left;">Sampling weight; 120x variation; EDA treats sample as unweighted</td>
</tr>
<tr class="odd">
<td style="text-align: left;">education_num</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">10.1</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">Clean ordered scale 1=Preschool to 16=Doctorate</td>
</tr>
<tr class="even">
<td style="text-align: left;">capital_gain</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">99999</td>
<td style="text-align: right;">1077.6</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Top-coded at 99,999 (159 rows); 91.7% are exactly 0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">capital_loss</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4356</td>
<td style="text-align: right;">87.3</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">No top-code evidence; 0 for 90%+ of rows</td>
</tr>
<tr class="even">
<td style="text-align: left;">hours_per_week</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">99</td>
<td style="text-align: right;">40.4</td>
<td style="text-align: right;">40</td>
<td style="text-align: left;">Top-coded at 99 (85 rows); 75th percentile = 45</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Two top-coded variables warrant specific attention:</p>
<p><strong>capital_gain tops out at $99,999.</strong> Exactly 159 rows (0.49%) report this value. This is a Census Bureau reporting ceiling, not a real data point — the actual capital gain for these respondents is unknown, only that it exceeds the cap. At the 95th percentile of all non-zero capital gains, the value is also $99,999, meaning the true distribution above roughly $15,000 is censored. For any downstream modeling, capital_gain cannot be treated as an unconstrained continuous variable without explicitly deciding how to handle this censored tail.</p>
<p><strong>hours_per_week tops out at 99.</strong> Exactly 85 rows (0.26%) report this value. The 99th percentile is 80, consistent with a Census convention of capping self-reported hours at 99. Practically, this top-code affects fewer than 1% of rows and has less analytical consequence than the capital_gain ceiling.</p>
</section>
<section id="categorical-level-inventory" class="level2">
<h2 class="anchored" data-anchor-id="categorical-level-inventory">Categorical Level Inventory</h2>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>cat_summary <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(workclass, education, marital_status, occupation, race, sex, native_country) <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">n_distinct</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"Column"</span>, <span class="at">values_to =</span> <span class="st">"Unique levels (excl. NA)"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(cat_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Column</th>
<th style="text-align: right;">Unique levels (excl. NA)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">workclass</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">education</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">marital_status</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">occupation</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">race</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">sex</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">native_country</td>
<td style="text-align: right;">41</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><code>native_country</code> has 41 distinct values, but is heavily concentrated: 89.6% of respondents were born in the United States. The next-largest origin country is Mexico (643 respondents, 2.0%), followed by a long tail with too few observations for reliable income comparisons. <code>native_country</code> is reported in the anomalies section but is not a primary focus of this analysis.</p>
</section>
<section id="income-class-split" class="level2">
<h2 class="anchored" data-anchor-id="income-class-split">Income Class Split</h2>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>tbl_income <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"../data/processed/tbl_income_split.rds"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(tbl_income)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">income</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">pct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">&lt;=50K</td>
<td style="text-align: right;">24720</td>
<td style="text-align: right;">75.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">&gt;50K</td>
<td style="text-align: right;">7841</td>
<td style="text-align: right;">24.1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>24.1% of the sample earns above $50,000</strong> — 7,841 of 32,561 respondents. This rate is the primary outcome throughout the analysis. See Phase 0 grounding in the Introduction for the external-benchmarked context for this figure.</p>
</section>
</section>
<section id="data-visualization-and-exploration" class="level1">
<h1>Data Visualization and Exploration</h1>
<section id="guiding-questions" class="level2">
<h2 class="anchored" data-anchor-id="guiding-questions">Guiding Questions</h2>
<p>Three structural findings from Phase 2 define the analysis:</p>
<ol type="1">
<li><strong>Education threshold.</strong> Income rate rises from near-zero at the lowest levels to over 70% for professional and doctoral degrees. Where exactly does the majority flip?</li>
<li><strong>Gender, marriage, and selection.</strong> The raw female vs.&nbsp;male income gap (10.9% vs.&nbsp;30.6%) nearly disappears within the married subgroup (45.5% vs.&nbsp;44.6%). The aggregate gap is almost entirely a matter of <em>who is in the labor force while married</em>, not pay discrimination visible in this data.</li>
<li><strong>Capital gains as investment access.</strong> 91.7% of the sample has zero capital gain. Among high earners, 21.4% have any capital gain vs.&nbsp;4.2% of low earners — a five-fold differential. Capital income is qualitatively different from wage income in this dataset.</li>
</ol>
<p>Two additional findings are explored: the occupational income structure (a 68-percentage-point spread from private household service to executive-managerial), and the age distribution of high earners (a tighter mid-career band than for lower earners).</p>
</section>
<section id="distributions" class="level2">
<h2 class="anchored" data-anchor-id="distributions">Distributions</h2>
<section id="numeric-variable-shapes" class="level3">
<h3 class="anchored" data-anchor-id="numeric-variable-shapes">Numeric variable shapes</h3>
<p>Most numeric variables in this dataset are well-behaved. <code>age</code> is slightly right-skewed (Pearson 0.35), with a working-age distribution covering 17–90. <code>education_num</code> is near-symmetric (0.09), a clean 1–16 ordinal scale. <code>hours_per_week</code> is highly concentrated at 40 — not a symmetric distribution, but a spike at full-time employment with tails in both directions, so standard outlier-detection formulas produce misleading results and are not applied here.</p>
<p><code>capital_gain</code> and <code>capital_loss</code> are a different kind of distribution entirely: <strong>zero-inflated.</strong> The IQR of capital_gain is exactly [0, 0] — three quarters of the sample has no capital income at all. The mean ($1,078) is pulled upward by the small minority with any gains; the median is $0. Treating this as a skewed continuous variable would obscure the most structurally important fact about it.</p>
</section>
<section id="age-and-the-mid-career-earnings-band" class="level3">
<h3 class="anchored" data-anchor-id="age-and-the-mid-career-earnings-band">Age and the mid-career earnings band</h3>
<!-- insight:age-income-band:start -->
<p>The age distributions for high and low earners are recognizably different in shape, not just in average.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>p_age <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"../data/processed/chart_age_density.rds"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>p_age</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/age-density-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>High earners (&gt;$50K) have a median age of 44 with a standard deviation of 10.5 years. Lower earners have a median of 34 and a standard deviation of 14.0. The difference in spread — not just center — is notable: the high-earning population is concentrated in a roughly 30–60 age band, with relatively few above 65 (where retirement reduces labor force participation) and almost none below 25. Lower earners, by contrast, are present in meaningful numbers from 17 upward and across a full working life.</p>
<p>This pattern is consistent with what a career-trajectory model would predict: high-earning positions require years of education and work experience to reach, which compresses their age distribution into the mid-career band. The younger left tail of the lower-earner distribution is largely students, entry-level workers, and early-career adults who have not yet reached income-earning years — not adults stuck at low wages across a full career.</p>
<!-- insight:age-income-band:end -->
</section>
</section>
<section id="trends" class="level2">
<h2 class="anchored" data-anchor-id="trends">Trends</h2>
<section id="education-and-the-threshold-that-almost-matters" class="level3">
<h3 class="anchored" data-anchor-id="education-and-the-threshold-that-almost-matters">Education and the threshold that almost matters</h3>
<!-- insight:education-threshold:start -->
<p>Education is the single strongest numeric predictor of income in this dataset (correlation 0.335 with the binary outcome, the highest of any numeric variable). But the relationship is not linear — it has a pronounced threshold shape.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>p_edu <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"../data/processed/chart_edu_trend.rds"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>p_edu</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/education-trend-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From Preschool through 12th grade, the income rate hovers below 8% across all levels — the differences between, say, 9th grade and 11th grade are small in absolute terms. At HS-grad the rate reaches 16%, and Some-college climbs to 19%. Then the slope steepens sharply: Bachelors jumps to 41.5%, Masters to 55.7%, and the 50% majority threshold is crossed only at Prof-school (73.4%) and Doctorate (74.1%).</p>
<p>The practical implication is a two-tier educational structure: completing a bachelor’s degree is a necessary-but-not-sufficient condition for majority odds of high income, and every level below it confers roughly similar low odds. The associate degrees (Assoc-voc: 26.1%, Assoc-acdm: 24.8%) sit roughly halfway between high school and bachelor’s — meaningful but short of the bachelor’s step change.</p>
<p>Note that education level is the variable, not years of education completed; “Prof-school” refers to professional school credentials (law, medicine, dentistry) rather than just 15 years of schooling, which explains why its income rate (73.4%) matches Doctorate (74.1%) rather than falling between Masters and Doctorate.</p>
<!-- insight:education-threshold:end -->
</section>
</section>
<section id="anomalies-and-domain-specific-findings" class="level2">
<h2 class="anchored" data-anchor-id="anomalies-and-domain-specific-findings">Anomalies and Domain-Specific Findings</h2>
<section id="the-gender-income-gap-and-what-it-actually-measures" class="level3">
<h3 class="anchored" data-anchor-id="the-gender-income-gap-and-what-it-actually-measures">The gender income gap and what it actually measures</h3>
<!-- insight:gender-marriage-gap:start -->
<p>The headline gender income gap in this dataset is substantial: 10.9% of women earn &gt;$50K, compared to 30.6% of men — a nearly three-to-one ratio. Taken at face value, this would suggest severe pay discrimination or occupational segregation.</p>
<p>Conditioning on marital status reveals a very different picture.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>p_gm <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"../data/processed/chart_gender_marriage.rds"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>p_gm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/gender-marriage-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Among <strong>married</strong> respondents, the gap nearly vanishes: married women earn &gt;$50K at a rate of <strong>45.5%</strong>, essentially identical to married men at <strong>44.6%</strong>. Among non-married respondents, the gap remains (female: 4.6%, male: 8.5%), but both rates are much lower than the married rates.</p>
<p>This is a <strong>selection effect, not an equal-pay story.</strong> In the 1994 labor market, married women who were in the labor force at all were heavily concentrated in professional and managerial roles — the women who stayed in full-time employment while married tended to be in exactly the occupations that pay above $50K. The aggregate 10.9% female rate is the average across all women in the sample, including large numbers working part-time, in lower-wage sectors, or with career interruptions. The aggregate number is real, but it measures who is in which labor-force category, not wage discrimination between men and women doing the same jobs.</p>
<p>What this data cannot say: whether women in the same role as men were paid equally. But looking within credentials rather than within marital status reveals that the picture is more complex than “married women earn as much as men.”</p>
<p><strong>Within credentials, the gap persists.</strong> Among bachelor’s degree holders: female 20.9% &gt;$50K vs.&nbsp;male 50.4% — a 2.4x differential. Among master’s holders: female 33.4% vs.&nbsp;male 65.7%. Only at the doctoral level do the rates begin to converge (female 58.1% vs.&nbsp;male 78.3%). The external benchmark is consistent: the 1994 Census P60-193 reports female-to-male earnings at 73% for full-time year-round workers overall, and specifically $35,378 vs.&nbsp;$49,228 for bachelor’s or higher holders. Women with bachelor’s degrees were earning 29% below the $50K threshold on average; men with bachelor’s degrees were essentially at it. The married-female finding (45.5%) reflects a highly selected subgroup — the women who remained in full-time professional employment while married in 1994 were concentrated in the highest-earning niches of each occupation. The broader picture is that the credential-income relationship operated along a 70–30 fault line by sex.</p>
<!-- insight:gender-marriage-gap:end -->
</section>
<section id="occupation-a-structural-income-floor" class="level3">
<h3 class="anchored" data-anchor-id="occupation-a-structural-income-floor">Occupation: a structural income floor</h3>
<!-- insight:occupation-ranking:start -->
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>p_occ <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"../data/processed/chart_occ_lollipop.rds"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>p_occ</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/occupation-ranking-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Across 14 named occupations, the income rate spans 68 percentage points — from Priv-house-serv (private household service: 0.7%) to Exec-managerial (48.4%). <strong>None</strong> of the 149 private household service workers in this sample earn above $50K. This is not a statistical edge case — it is the floor of the occupational structure, where wages are constrained by the ability-to-pay of individual households rather than corporate employment markets. The occupation acts as a near-absolute income ceiling for the people in it.</p>
<p>The top two occupations (Exec-managerial and Prof-specialty) together account for 8,206 respondents — roughly 25% of the sample — and both hover near or above 45%. Below them is a large middle tier (Protective-serv through Transport-moving, 20–32%), then a sharp drop into the administrative and service occupations (Adm-clerical through Farming-fishing, 11–13%), and a bottom cluster (Handlers-cleaners, Other-service, Priv-house-serv) at single digits.</p>
<p>Occupation and education are correlated predictors — workers in higher-income occupations tend to have higher education levels. Neither can be called the “cause” of income at this level of analysis; both reflect accumulated structural position.</p>
<!-- insight:occupation-ranking:end -->
</section>
<section id="capital-gains-investment-income-as-a-high-earner-signal" class="level3">
<h3 class="anchored" data-anchor-id="capital-gains-investment-income-as-a-high-earner-signal">Capital gains: investment income as a high-earner signal</h3>
<!-- insight:capital-gains-concentration:start -->
<p>Capital gains are, for most people in this sample, simply absent.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>p_cg <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"../data/processed/chart_capital_gain.rds"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>p_cg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/capital-gains-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p><strong>91.7% of all respondents report $0 in capital gains.</strong> Among the remaining 8.3%, there is wide variation: the median non-zero gain is $7,896 among high earners and $3,273 among lower earners. The pattern reverses at the top: 2% of high earners hit the $99,999 reporting ceiling (suggesting actual gains well above that figure), versus essentially zero among lower earners.</p>
<p>The five-fold difference in any-capital-gain prevalence (4.2% vs.&nbsp;21.4%) is the cleanest signal in the dataset that high income and investment income co-occur — people above the $50K wage threshold are also, at much higher rates, building wealth through investment returns. This is not simply a case of people investing more because they have more money left after expenses (though that is likely part of the story); it also reflects differential access to investment vehicles, financial literacy, and employer-offered stock programs, all of which were concentrated in higher-income professional roles in 1994.</p>
<p>The $99,999 top-code means that for high-earning investors, the true scale of capital gains is unknown and potentially much larger than the data shows. Any summary statistic for capital_gain that includes the censored rows should be read as a lower bound for those respondents.</p>
<!-- insight:capital-gains-concentration:end -->
</section>
<section id="race-disparities-a-coarse-but-real-signal" class="level3">
<h3 class="anchored" data-anchor-id="race-disparities-a-coarse-but-real-signal">Race disparities: a coarse but real signal</h3>
<p>Income rates vary substantially by race in this sample: Asian-Pacific Islander (26.6%) and White (25.6%) respondents have nearly identical rates; Black (12.4%), American Indian/Eskimo (11.6%), and Other (9.2%) respondents have rates roughly half as high. These are coarse univariate numbers — race interacts with occupation, education, and nativity in ways that a single proportion cannot disentangle. The raw disparity is real and worth naming, but the mechanism cannot be established from a comparison of these proportions alone.</p>
</section>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<!-- insight:conclusion:start -->
<p>The 1994 CPS Adult dataset shows a labor market where high individual income ($50K, roughly equivalent to $105,000 in today’s dollars) was relatively rare — captured by 24% of the working adults in the sample — and concentrated along three structural dimensions: educational credentials, occupational sector, and career stage.</p>
<p>Education functions as a near-binary gate in this data. Below a bachelor’s degree, income rates stay in single digits regardless of grade level completed; at the bachelor’s degree, the rate jumps to 41%; and above it, the majority of credential-holders (Masters, Prof-school, Doctorate) earn above the threshold. This is not a smooth gradient — it is a structural discontinuity that the labor market was enforcing even in 1994, before credential inflation had raised the floor further.</p>
<p>Occupation reinforces this structure but does not simply duplicate it: the 68-point spread between private household service (0.7%) and executive-managerial (48.4%) reflects that sector matters independently of individual qualifications. The workers at the bottom of the occupational ranking are not simply less-educated workers — they are in roles where the entire wage structure is constrained by who is paying.</p>
<p>The gender income gap story is more nuanced than the headline 3:1 ratio suggests. Married women and married men in this sample earn above the threshold at essentially identical rates (45.5% vs.&nbsp;44.6%). The aggregate gap is almost entirely a 1994 labor-force-participation story: far fewer women were in the married-professional category than men. This data cannot speak to whether men and women in the same role were paid the same; it can say that among those who reached professional-managerial roles and remained in the workforce while married, the income outcome was remarkably symmetric.</p>
<p>The capital gains finding is the one that most clearly reveals something about how wealth works rather than just how wages work. For 92% of this sample, investment income is absent. For high earners, it is present at 5x the rate of lower earners. Wage income and investment income do not simply track each other — they appear as distinct layers of the income distribution, with the investment layer accessible primarily to those who have already cleared the wage threshold.</p>
<p><strong>Representativeness caveats.</strong> This is a 1994 cross-sectional extract, and the US labor market has shifted substantially since: the college wage premium has widened, the gig economy has reshaped workclass categories, and the demographic composition of the workforce has changed. The $50K threshold, equivalent to roughly $106K today (BLS CPI-U), places this analysis in the upper-quartile income conversation, not the median-income conversation. Any direct application of these findings to current policy or workforce planning should first establish whether the structural patterns have held, sharpened, or reversed.</p>
<p>One representativeness concern is specific to the sample itself, independent of era: the dataset contains 33.1% female respondents against an actual 1994 female labor force share of 45.9% (BLS EcoPro Table 1). The fnlwgt weights would correct for this in a weighted analysis; all income-by-sex comparisons in this report are unweighted and thus based on a male-skewed sample. The specific magnitude of gender-related findings should be read with this caveat in mind.</p>
<!-- insight:conclusion:end -->
<section id="analysis-approach-next-phase" class="level2">
<h2 class="anchored" data-anchor-id="analysis-approach-next-phase">Analysis Approach (Next Phase)</h2>
<p>The five findings above define the structural landscape of the dataset. A natural next step is binary classification modeling — predicting the &gt;$50K label from the available features, with special attention to whether the model reproduces or obscures the demographic disparities surfaced here. Given the data quality issues identified (top-coded capital_gain, co-missing workclass/occupation), any modeling pipeline would need explicit decisions about imputation strategy, capital_gain treatment, and whether fnlwgt sampling weights should be incorporated.</p>
</section>
</section>
<section id="technical-notes" class="level1">
<h1>Technical Notes</h1>
<section id="reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="reproducibility">Reproducibility</h2>
<ul>
<li><strong>Environment:</strong> R 4.5.x, tidyverse 2.0.0, arrow 14.x</li>
<li><strong>To reproduce from raw data:</strong>
<ol type="1">
<li>From the project root, run <code>Rscript R/01_prep.R</code> — loads raw data, applies column names, replaces <code>?</code> nulls, writes <code>data/processed/adult_clean.parquet</code></li>
<li>Run <code>Rscript R/02_phase1_tables.R</code> — writes Phase 1 summary tables as <code>.rds</code> to <code>data/processed/</code></li>
<li>Run <code>Rscript R/03_charts.R</code> — builds all chart objects and saves as <code>.rds</code> to <code>data/processed/</code>; also exports standalone PNGs to <code>output/figures/</code></li>
<li>Render this report: <code>quarto render output/report.qmd</code></li>
</ol></li>
<li>The report loads cached objects from <code>data/processed/</code> — it does not re-read <code>data/raw/</code> directly.</li>
</ul>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ol type="1">
<li>US Census Bureau. <em>Income, Poverty, and Valuation of Noncash Benefits: 1994.</em> Current Population Reports P60-189, 1996. Source of 1994 income medians by sex and education.</li>
<li>US Census Bureau. <em>Money Income in the United States: 1995.</em> Current Population Reports P60-193, 1996. Source of the female-to-male earnings ratio (~73%) for full-time year-round workers.</li>
<li>Bureau of Labor Statistics. <em>Employment Projections — Table 1: Civilian labor force by age, gender, race, and ethnicity, 1994–2024.</em> bls.gov/news.release/ecopro.t01.htm. Source of 1994 labor force racial and sex composition benchmarks.</li>
<li>Bureau of Labor Statistics. <em>Consumer Price Index for All Urban Consumers (CPI-U).</em> Annual average 1994: 148.2; 2024: 313.7. Source of inflation conversion ($50K in 1994 ≈ $105,800 in 2024).</li>
<li>Social Security Administration. <em>National Average Wage Index Series.</em> ssa.gov/oact/cola/awiseries.html. Source of 1994 national average wage: $23,754.</li>
<li>National Center for Education Statistics. <em>Digest of Education Statistics 1996, Table 375.</em> Median earnings by education level and sex, 1994 full-time year-round workers.</li>
<li>National Center for Education Statistics. <em>Digest of Education Statistics 1995, Table 371.</em> Unemployment rates by education level, 1994.</li>
<li>UCI Machine Learning Repository. <em>Adult Data Set.</em> archive.ics.uci.edu/ml/datasets/adult — dataset column documentation only; not an external grounding source.</li>
<li>Becker, Barry and Kohavi, Ronny. <em>Scaling Up the Accuracy of Naive-Bayes Classifiers: A Decision-Tree Hybrid.</em> KDD-96, 1996. — original dataset publication; cited for provenance only.</li>
</ol>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>