<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kwaku EDA">
<meta name="dcterms.date" content="2026-07-22">

<title>Adult (Census Income) Dataset — Exploratory Data Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-8ffd5f67044e5306d9846f29df41dda5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a>
  <ul class="collapse">
  <li><a href="#source" id="toc-source" class="nav-link" data-scroll-target="#source">Source</a></li>
  <li><a href="#reading-the-data" id="toc-reading-the-data" class="nav-link" data-scroll-target="#reading-the-data">Reading the Data</a></li>
  </ul></li>
  <li><a href="#data-quality-checks" id="toc-data-quality-checks" class="nav-link" data-scroll-target="#data-quality-checks">Data Quality Checks</a>
  <ul class="collapse">
  <li><a href="#record-count-verification" id="toc-record-count-verification" class="nav-link" data-scroll-target="#record-count-verification">Record Count Verification</a></li>
  <li><a href="#null-missing-value-check" id="toc-null-missing-value-check" class="nav-link" data-scroll-target="#null-missing-value-check">Null / Missing Value Check</a></li>
  <li><a href="#numeric-range-validation" id="toc-numeric-range-validation" class="nav-link" data-scroll-target="#numeric-range-validation">Numeric Range Validation</a></li>
  <li><a href="#categorical-level-inventory" id="toc-categorical-level-inventory" class="nav-link" data-scroll-target="#categorical-level-inventory">Categorical Level Inventory</a></li>
  </ul></li>
  <li><a href="#data-visualization-and-exploration" id="toc-data-visualization-and-exploration" class="nav-link" data-scroll-target="#data-visualization-and-exploration">Data Visualization and Exploration</a>
  <ul class="collapse">
  <li><a href="#questions" id="toc-questions" class="nav-link" data-scroll-target="#questions">Questions</a></li>
  <li><a href="#distributions" id="toc-distributions" class="nav-link" data-scroll-target="#distributions">Distributions</a></li>
  <li><a href="#trends" id="toc-trends" class="nav-link" data-scroll-target="#trends">Trends</a></li>
  <li><a href="#occupation-already-authoritatively-classified" id="toc-occupation-already-authoritatively-classified" class="nav-link" data-scroll-target="#occupation-already-authoritatively-classified">Occupation, Already Authoritatively Classified</a></li>
  <li><a href="#anomalies-and-domain-specific-findings" id="toc-anomalies-and-domain-specific-findings" class="nav-link" data-scroll-target="#anomalies-and-domain-specific-findings">Anomalies and Domain-Specific Findings</a>
  <ul class="collapse">
  <li><a href="#the-sex-gap-that-mostly-isnt-there-once-you-control-for-marriage" id="toc-the-sex-gap-that-mostly-isnt-there-once-you-control-for-marriage" class="nav-link" data-scroll-target="#the-sex-gap-that-mostly-isnt-there-once-you-control-for-marriage">The sex gap that (mostly) isn’t there once you control for marriage</a></li>
  <li><a href="#is-50000-a-demanding-bar-in-1994-terms" id="toc-is-50000-a-demanding-bar-in-1994-terms" class="nav-link" data-scroll-target="#is-50000-a-demanding-bar-in-1994-terms">Is $50,000 a demanding bar in 1994 terms?</a></li>
  <li><a href="#unreported-employer-type-is-not-the-same-as-not-working" id="toc-unreported-employer-type-is-not-the-same-as-not-working" class="nav-link" data-scroll-target="#unreported-employer-type-is-not-the-same-as-not-working">Unreported employer type is not the same as not working</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a>
  <ul class="collapse">
  <li><a href="#analysis-approach-next-phase" id="toc-analysis-approach-next-phase" class="nav-link" data-scroll-target="#analysis-approach-next-phase">Analysis Approach (Next Phase)</a></li>
  </ul></li>
  <li><a href="#technical-notes" id="toc-technical-notes" class="nav-link" data-scroll-target="#technical-notes">Technical Notes</a>
  <ul class="collapse">
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility">Reproducibility</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Adult (Census Income) Dataset — Exploratory Data Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kwaku EDA </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 22, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>This dataset is a 32,561-record extract from the 1994 U.S. Census Bureau’s Current Population Survey (CPS), assembled by Barry Becker and donated to the UCI Machine Learning Repository by Ronny Kohavi and Barry Becker. Each row is one adult respondent, described by 14 demographic and employment attributes (age, education, occupation, marital status, hours worked, and so on), with a binary outcome: whether that person’s individual income exceeded $50,000 in the year surveyed. Becker restricted the extract to records with <code>age &gt; 16</code>, positive adjusted gross income basis, a valid sampling weight, and <code>hours-per-week &gt; 0</code> — so this is a working-adult population, not the general public.</p>
<p>This analysis asks six specific questions, selected from a larger candidate pool generated by sweeping every variable in the schema against the income outcome (the full pool, with reasoning for what didn’t make the cut, is in <code>R/candidate_questions.md</code>):</p>
<ol type="1">
<li>Where, precisely, does the education–income relationship cross the point where a majority of people clear $50K?</li>
<li>Which occupations are most and least associated with high income — and is the 14-level raw <code>occupation</code> coding an arbitrary grouping, or does it already correspond to an authoritative external classification?</li>
<li>The dataset shows a large aggregate income gap between men and women. Is that gap uniform across the data, or concentrated in a specific subpopulation?</li>
<li>About 1 in 18 respondents didn’t report an employer type (<code>workclass</code>). Who are they, and does their condition actually resemble unemployment?</li>
<li>The capital-gains column has a hard ceiling at $99,999. What does that mean for anyone using the column downstream?</li>
<li>Is a $50,000 <em>individual</em> income threshold a demanding bar to clear in 1994 terms — and does that context explain why only about a quarter of this working population clears it?</li>
</ol>
</section>
<section id="the-data" class="level1">
<h1>The Data</h1>
<section id="source" class="level2">
<h2 class="anchored" data-anchor-id="source">Source</h2>
<p>Collected via the CPS in 1994 and extracted/donated by Barry Becker (Silicon Graphics) later that year; first cited in Kohavi (1996), “Scaling Up the Accuracy of Naive-Bayes Classifiers: a Decision-Tree Hybrid.” The data is now three decades old. Every comparison below against a present-day intuition (e.g., “$50K sounds low today”) is explicitly reframed in 1994 terms rather than left as an implicit, misleading comparison — see “Is $50,000 a demanding bar in 1994 terms?” below.</p>
</section>
<section id="reading-the-data" class="level2">
<h2 class="anchored" data-anchor-id="reading-the-data">Reading the Data</h2>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>col_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"workclass"</span>, <span class="st">"fnlwgt"</span>, <span class="st">"education"</span>, <span class="st">"education_num"</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               <span class="st">"marital_status"</span>, <span class="st">"occupation"</span>, <span class="st">"relationship"</span>, <span class="st">"race"</span>, <span class="st">"sex"</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>               <span class="st">"capital_gain"</span>, <span class="st">"capital_loss"</span>, <span class="st">"hours_per_week"</span>, <span class="st">"native_country"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>               <span class="st">"income"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../data/raw/adult.data"</span>, <span class="at">col_names =</span> col_names, <span class="at">na =</span> <span class="fu">character</span>(),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trim_ws =</span> <span class="cn">TRUE</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.character), str_trim))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">"../data/processed/adult_clean.parquet"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong>Data dictionary</strong> (condensed from <code>adult.names</code>): <code>fnlwgt</code> is <em>not</em> a personal attribute — it is the CPS sampling weight, the Census Bureau’s estimate of how many people in the actual U.S. population this one record represents, controlled to independent population totals by state, Hispanic origin, race, age, and sex. It should never be treated as an ordinary numeric predictor. <code>education</code> and <code>education_num</code> are perfectly redundant (verified below) — one ordinal encoding of the other.</p>
</section>
</section>
<section id="data-quality-checks" class="level1">
<h1>Data Quality Checks</h1>
<section id="record-count-verification" class="level2">
<h2 class="anchored" data-anchor-id="record-count-verification">Record Count Verification</h2>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_parquet</span>(<span class="st">"../data/processed/tbl_record_count.parquet"</span>) <span class="sc">%&gt;%</span> knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 24%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: right;">Expected</th>
<th style="text-align: right;">Actual</th>
<th style="text-align: left;">Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rows (train split)</td>
<td style="text-align: right;">32561</td>
<td style="text-align: right;">32561</td>
<td style="text-align: left;">Matches adult.names documentation exactly.</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Matches the documented train-split count exactly.</p>
</section>
<section id="null-missing-value-check" class="level2">
<h2 class="anchored" data-anchor-id="null-missing-value-check">Null / Missing Value Check</h2>
<p>A direct <code>NA</code> check across all 15 columns comes back completely clean — but the codebook states that unknown values were encoded as the literal string <code>"?"</code> before publication, not as blanks. Checking for that literal specifically finds missingness concentrated in exactly three columns:</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_parquet</span>(<span class="st">"../data/processed/tbl_nulls.parquet"</span>) <span class="sc">%&gt;%</span> knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 57%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">column</th>
<th style="text-align: right;">n_disguised_na</th>
<th style="text-align: right;">pct_of_rows</th>
<th style="text-align: left;">handling</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">workclass</td>
<td style="text-align: right;">1836</td>
<td style="text-align: right;">5.64</td>
<td style="text-align: left;">Recoded ‘?’ -&gt; NA in data/processed/adult_clean.parquet</td>
</tr>
<tr class="even">
<td style="text-align: left;">occupation</td>
<td style="text-align: right;">1843</td>
<td style="text-align: right;">5.66</td>
<td style="text-align: left;">Recoded ‘?’ -&gt; NA in data/processed/adult_clean.parquet</td>
</tr>
<tr class="odd">
<td style="text-align: left;">native_country</td>
<td style="text-align: right;">583</td>
<td style="text-align: right;">1.79</td>
<td style="text-align: left;">Recoded ‘?’ -&gt; NA in data/processed/adult_clean.parquet</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Handling: <code>"?"</code> recoded to true <code>NA</code> in <code>data/processed/adult_clean.parquet</code>, so downstream summaries don’t silently treat “unknown” as its own factor level.</p>
<p><strong>Missingness pattern.</strong> <code>workclass</code> and <code>occupation</code> are missing on almost exactly the same rows — every one of the 1,836 <code>workclass</code>-NA rows is also <code>occupation</code>-NA, and the 7 extra <code>occupation</code>-only-NA rows are exactly the respondents who report <code>workclass == "Never-worked"</code> (no employer, so naturally no occupation either). This is structural, not scattered. <code>native_country</code>’s missingness (583 rows), by contrast, barely overlaps with the other two (27 rows in common) and looks scattered — no identifiable pattern tying it to employment status.</p>
</section>
<section id="numeric-range-validation" class="level2">
<h2 class="anchored" data-anchor-id="numeric-range-validation">Numeric Range Validation</h2>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_parquet</span>(<span class="st">"../data/processed/tbl_numeric_ranges.parquet"</span>) <span class="sc">%&gt;%</span> knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">column</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">38.6</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">13.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">fnlwgt</td>
<td style="text-align: right;">12285</td>
<td style="text-align: right;">1484705</td>
<td style="text-align: right;">189778.4</td>
<td style="text-align: right;">178356</td>
<td style="text-align: right;">105550.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">education_num</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">10.1</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">2.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">capital_gain</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">99999</td>
<td style="text-align: right;">1077.6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">7385.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">capital_loss</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4356</td>
<td style="text-align: right;">87.3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">403.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">hours_per_week</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">99</td>
<td style="text-align: right;">40.4</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">12.3</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>All ranges are plausible for a CPS extract pre-filtered to <code>age &gt; 16</code> and <code>hours-per-week &gt; 0</code> — no negative ages, no zero-hour work weeks, no out-of-range education codes. Two values need a closer look, not because they’re implausible but because of what they represent:</p>
<!-- insight:capital-gain-topcode:start -->
<ul>
<li><strong><code>capital_gain</code> has a hard ceiling, not a natural tail.</strong> 159 of 32,561 rows (0.49% of all rows; 5.9% of the 2,712 rows with any nonzero capital gain) sit at <em>exactly</em> 99,999 — a spike of exact duplicates at the top of the range, not a smoothly thinning tail. That is the signature of Census-style income top-coding: a disclosure-avoidance practice where amounts above a threshold are truncated to one ceiling value rather than published exactly, to prevent re-identifying very-high-income respondents. All 159 topcoded rows carry the <code>&gt;50K</code> label, which is internally consistent but also means: <strong>a model or statistic that treats 99,999 as a literal dollar figure is misreading it.</strong> The true values are unknown, only bounded below. This needs a deliberate decision before any modeling — drop, cap-and-flag, or treat topcoding as its own binary indicator — not silent inclusion as ordinary numeric data. <!-- insight:capital-gain-topcode:end --></li>
<li><strong><code>hours_per_week</code>’s distribution is tighter than its full min/max range suggests.</strong> An IQR-based outlier scan flags 27.7% of rows as “outliers” — but that’s an artifact of the variable’s shape (a sharp mode at exactly 40, with a long, entirely plausible tail from 1 to 99 hours for part-time and overtime work), not a data-quality problem. Shown as a plain distribution below rather than framed as an outlier issue.</li>
</ul>
</section>
<section id="categorical-level-inventory" class="level2">
<h2 class="anchored" data-anchor-id="categorical-level-inventory">Categorical Level Inventory</h2>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_parquet</span>(<span class="st">"../data/processed/tbl_categorical_levels.parquet"</span>) <span class="sc">%&gt;%</span> knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">column</th>
<th style="text-align: right;">n_levels</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">workclass</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">education</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">marital_status</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">occupation</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">relationship</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">race</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sex</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">native_country</td>
<td style="text-align: right;">42</td>
</tr>
<tr class="odd">
<td style="text-align: left;">income</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><code>native_country</code> (42 levels) and <code>occupation</code> (15 levels) are the two columns with enough categories that a raw bar/lollipop chart risks becoming unreadable or uninformative — <code>occupation</code> is checked against an authoritative external classification in the Visualization section below (it turns out to already match one, rather than needing to be collapsed). Verified separately that <code>education</code>/<code>education_num</code> are a strict 1-to-1 mapping (16 distinct pairs for 16 distinct education strings), confirming the redundancy noted in the data dictionary above. A duplicate-row scan also found 24 fully-duplicate records (all columns including <code>income</code> identical) out of 32,561 — small enough not to materially affect any statistic in this report, left in rather than silently dropped, and noted here rather than reconciled against the codebook’s own “6 duplicate/conflicting instances” figure (that figure describes the combined train+test file, not the train split alone, and the two numbers don’t cleanly reconcile — flagged as an open question rather than resolved by guessing).</p>
</section>
</section>
<section id="data-visualization-and-exploration" class="level1">
<h1>Data Visualization and Exploration</h1>
<section id="questions" class="level2">
<h2 class="anchored" data-anchor-id="questions">Questions</h2>
<ol type="1">
<li>Where does the education–income relationship cross 50%?</li>
<li>How does income vary by occupation, and does the raw 14-level coding already correspond to an authoritative external classification?</li>
<li>Does the aggregate sex gap in income hold within every subgroup, or is it concentrated somewhere specific?</li>
<li>What does the <code>workclass</code>-unreported population actually look like?</li>
<li>What does the <code>capital_gain</code> topcode mean for this column’s usability?</li>
<li>Is $50K a demanding threshold in 1994 terms?</li>
</ol>
</section>
<section id="distributions" class="level2">
<h2 class="anchored" data-anchor-id="distributions">Distributions</h2>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">readRDS</span>(<span class="st">"../data/processed/chart_hours_dist.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/hours-dist-r-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Hours worked concentrates overwhelmingly at the standard 40-hour week, with real (not error-driven) mass on both sides — a long-standing pattern in labor statistics, not a quirk of this sample.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">readRDS</span>(<span class="st">"../data/processed/chart_capital_gain.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/capgain-dist-r-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Among the 2,712 respondents (8.3% of the sample) with any nonzero capital gain, the distribution thins out smoothly until the very top — where it spikes back up at exactly 99,999. That spike is not a natural continuation of the trend; it is where the Census Bureau’s disclosure-avoidance topcoding cuts in.</p>
</section>
<section id="trends" class="level2">
<h2 class="anchored" data-anchor-id="trends">Trends</h2>
<!-- insight:education-threshold:start -->
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">readRDS</span>(<span class="st">"../data/processed/chart_education_trend.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/education-trend-r-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>The relationship between education and the odds of earning over $50K is not gently increasing — it is close to flat through secondary schooling (every level from Preschool through 12th grade sits under 8%), and then rises steeply from HS-grad onward. The 50% line is crossed between a Bachelor’s degree (41.5% earn &gt;$50K) and a Master’s degree (55.7%) — at roughly the Bachelor’s-plus-some-graduate-coursework point on this ordinal scale. Beyond that, the professional and doctoral tracks (Prof-school 73.4%, Doctorate 74.1%) cluster together near three-quarters, rather than continuing to climb — the returns to formal education taper once a research or professional credential is reached, at least as this single-year income threshold measures it. <!-- insight:education-threshold:end --></p>
</section>
<section id="occupation-already-authoritatively-classified" class="level2">
<h2 class="anchored" data-anchor-id="occupation-already-authoritatively-classified">Occupation, Already Authoritatively Classified</h2>
<!-- insight:occupation-ranking:start -->
<p>Before ranking occupations, it’s worth checking whether the raw 14-level <code>occupation</code> field is an arbitrary coding that needs collapsing, or something more principled. It turns out to be the latter: the U.S. Census Bureau’s own 1990 occupation classification scheme (documented in Census Technical Paper 65, <em>The Relationship Between the 1990 Census and Census 2000 Industry and Occupation Classification Systems</em>) groups all civilian employed persons into 13 major occupation groups — Executive/administrative/managerial, Professional specialty, Technicians and related support, Sales, Administrative support (clerical), Private household, Protective service, Service (except protective/household), Farming/forestry/fishing, Precision production/craft/repair, Machine operators/assemblers/inspectors, Transportation/material moving, and Handlers/equipment cleaners/laborers — plus Armed Forces as a separate category outside that civilian scheme. This dataset’s 14 <code>occupation</code> labels are near-verbatim abbreviations of exactly those 13 groups plus Armed Forces, a clean 1-to-1 correspondence. In other words, this field doesn’t need an external scheme applied to collapse it — it already <em>is</em> the Census Bureau’s own authoritative major-group taxonomy, carried through from the original 1994 CPS coding. (A coarser collapse — e.g., white-collar/service/blue-collar — would be a further aggregation layered on top of this, and worth labeling explicitly as this analysis’s own grouping rather than implying it’s independently Census-sanctioned; not applied here since the 13/14-group view is already an authoritative, decision-relevant level of detail.)</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">readRDS</span>(<span class="st">"../data/processed/chart_occupation_lollipop.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/occupation-lollipop-r-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>The spread is the widest of any categorical variable checked in this analysis: Executive/managerial and Professional specialty roles clear $50K roughly half the time (48.4% and 44.9%), while Private household service work sits at 0.7% — a 69-fold difference in rate between the top and bottom occupation groups. Farming-fishing and Handlers-cleaners round out the bottom alongside Other-service, all under 12%. <!-- insight:occupation-ranking:end --></p>
</section>
<section id="anomalies-and-domain-specific-findings" class="level2">
<h2 class="anchored" data-anchor-id="anomalies-and-domain-specific-findings">Anomalies and Domain-Specific Findings</h2>
<section id="the-sex-gap-that-mostly-isnt-there-once-you-control-for-marriage" class="level3">
<h3 class="anchored" data-anchor-id="the-sex-gap-that-mostly-isnt-there-once-you-control-for-marriage">The sex gap that (mostly) isn’t there once you control for marriage</h3>
<!-- insight:sex-gap-marriage:start -->
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">readRDS</span>(<span class="st">"../data/processed/chart_sex_gap.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/sex-gap-r-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Across the full dataset, men clear $50K at nearly three times the rate of women (30.6% vs.&nbsp;11.0%) — a large, real gap, and the kind of aggregate figure that would normally anchor a headline. But narrowing to respondents who are married with spouse present (<code>marital_status == "Married-civ-spouse"</code>) collapses that gap almost entirely: 44.6% of married men and 45.5% of married women clear $50K, despite wives in this subgroup working noticeably fewer average hours per week than husbands (36.7 vs.&nbsp;44.1). The <code>relationship</code> column’s <code>Wife</code> category alone (n=1,566) shows a 47.5% rate — fractionally <em>above</em> <code>Husband</code>’s 44.9%.</p>
<p>This isn’t evidence the sex gap is illusory — it’s evidence the gap is unevenly distributed. The much larger population of women who are <code>Own-child</code> (1.1% clear $50K; mean age 24.6, mostly young adults still living at home), <code>Unmarried</code> (4.2%), or <code>Not-in-family</code> (7.3%) is what pulls the aggregate female rate down to 11.0%. Married women in this sample are not earning less than their husbands individually — the aggregate gap is concentrated almost entirely outside marriage, in a much younger, differently-situated population that a single “women earn less” headline would flatten into one number. Separately, <code>sex</code> shows a strong association with <code>occupation</code> (Cramér’s V = 0.434 — comparable in strength to <code>marital_status</code>’s association with income) — women in this sample are concentrated in Adm-clerical (25.5% of employed women) and Other-service (18.1%), men in Craft-repair (18.7%) and Exec-managerial (14.0%) — a plausible structural channel for the part of the gap that persists outside marriage, even without a formal decomposition here. <!-- insight:sex-gap-marriage:end --></p>
</section>
<section id="is-50000-a-demanding-bar-in-1994-terms" class="level3">
<h3 class="anchored" data-anchor-id="is-50000-a-demanding-bar-in-1994-terms">Is $50,000 a demanding bar in 1994 terms?</h3>
<!-- insight:external-benchmark-1994:start -->
<p>Grounding this dataset’s own 24.08% positive rate requires two things: an independent 1994-era income benchmark, and care about which income unit is being compared. The U.S. Census Bureau’s <em>Income, Poverty, and Valuation of Noncash Benefits: 1994</em> (Current Population Reports P60-189) puts <strong>median household income at $32,264</strong> in 1994. The Bureau’s Historical Income Tables (Table H-1) put the boundary of the fourth income quintile at <strong>$62,841</strong> and the third at <strong>$40,100</strong> — so $50,000 in <em>household</em> income fell inside the fourth-highest fifth of all U.S. households, roughly the top 30%.</p>
<p>But this dataset’s outcome is <strong>individual</strong>, not household, income — and the individual-level benchmark makes $50K look considerably more demanding, not less. The Census Bureau’s Table P-38 puts 1994 <strong>median annual earnings for full-time, year-round male workers at $30,854</strong>, and for women at $22,205 — meaning the median full-time, year-round <em>male</em> earner, the higher-earning group by sex, didn’t clear $31,000, let alone $50,000. Per-capita money income across the whole population (workers and non-workers) was $16,555. Against that backdrop, $50,000 in individual annual income in 1994 was a genuinely elite threshold, well above what even a typical full-time worker earned.</p>
<p>That reframes the dataset’s 24% positive rate: it isn’t evidence that a quarter of 1994 America cleared $50K individually — it’s the product of this dataset’s own extraction filters (working adults with <code>hours-per-week &gt; 0</code> and positive income, which already excludes retirees, students, the unemployed, and non-earners) selecting a population skewed toward the higher end of individual earners, still clearing an individually demanding bar at a meaningfully lower rate than a household-income comparison alone would suggest.</p>
<p>The same unit-matching caution applies to two other comparisons this dataset invites. The sex gap seen here (30.6% of men vs.&nbsp;11.0% of women clear the $50K individual threshold) is not directly comparable in magnitude to the contemporaneous Census P-38 finding that women’s median full-time annual earnings were <strong>72.0% of men’s</strong> in 1994 ($22,205 vs.&nbsp;$30,854) — one is a threshold-crossing-rate gap, the other a median-ratio gap, different measures of a related but distinct phenomenon; both point the same direction, but only the direction, not the magnitude, transfers. Likewise, the race gap in this data (White 25.6% vs.&nbsp;Black 12.4% clearing $50K) runs in the same direction as, but isn’t the same statistic as, the Census Bureau’s 1994 Black-to-White <em>household</em> median income ratio of <strong>61.8%</strong> (Table H-5: $21,027 vs.&nbsp;$34,028) — again a household-level median-ratio figure being used only to confirm direction, not magnitude, against this dataset’s individual-level threshold-crossing figures. One caution worth naming plainly: a White/Black comparison alone would understate how much this dataset resists a simple “White vs.&nbsp;everyone else” binary. Respondents recorded as Asian-Pac-Islander clear $50K at 26.6% — fractionally <em>above</em> the White rate of 25.6% — while Amer-Indian-Eskimo (11.6%) and Other (9.2%) sit closer to the Black rate. A framing that collapses <code>race</code> into “White vs.&nbsp;non-White” would misrepresent this specific dataset’s own pattern. <!-- insight:external-benchmark-1994:end --></p>
</section>
<section id="unreported-employer-type-is-not-the-same-as-not-working" class="level3">
<h3 class="anchored" data-anchor-id="unreported-employer-type-is-not-the-same-as-not-working">Unreported employer type is not the same as not working</h3>
<!-- insight:workclass-unreported:start -->
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">readRDS</span>(<span class="st">"../data/processed/chart_workclass_rank.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/workclass-rank-r-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>The natural first guess for “employer type unreported” is “not currently in the labor force” — but this dataset’s own extraction criteria already required <code>hours-per-week &gt; 0</code> for every row, so a genuinely non-working respondent could not appear at all. Checked directly: the 1,836 <code>workclass</code>-unreported respondents report a mean of 31.9 hours per week, and not one of them reports zero hours. They are working real hours and either declined to specify, or the survey could not resolve, what kind of employer they have. Their income profile is closer to <code>Never-worked</code>/<code>Without-pay</code> (both near 0%, though on tiny samples of 7 and 14) than to <code>Private</code> (21.9%) — a distinct labor-market position, not simply “unemployed,” and one worth carrying as its own category rather than dropping or imputing it into <code>Private</code> by default in any downstream use. <!-- insight:workclass-unreported:end --></p>
</section>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This dataset is a genuinely informative snapshot of the U.S. working population in 1994, but three things need to stay attached to any claim drawn from it. First, the outcome variable is <em>individual</em>, not household, income — a $50,000 individual threshold is a much higher bar than a $50,000 household threshold, and every comparison to a household-income statistic needs that unit named explicitly rather than assumed away. Second, several columns carry Census-methodology artifacts that look like ordinary data until checked directly: <code>capital_gain</code>’s topcoding at 99,999, <code>fnlwgt</code>’s status as a sampling weight rather than a personal attribute, and <code>workclass</code>’s structurally (not randomly) missing values. Any of these treated naively — as literal dollar amounts, an ordinary numeric feature, or random missingness safe to drop — would produce a plausible-looking but wrong analysis. Third, the data is three decades old: dollar thresholds, occupational structure, and labor-force participation have all shifted since 1994, so any claim about “what predicts income” from this data describes 1994, not the present, unless restated with that caveat.</p>
<p>What the data does say clearly: education is the single steepest, most monotonic predictor of the $50K threshold in this sample, crossing from a minority to a majority outcome specifically between a Bachelor’s and a Master’s degree. The often-cited sex income gap is real in aggregate but concentrated almost entirely outside marriage — a pattern easy to miss if the analysis stops at the aggregate <code>sex</code> breakdown and never conditions on <code>relationship</code> or <code>marital_status</code>. And a meaningful slice of the “missing data” in this dataset (<code>workclass</code>/<code>occupation</code>) is not missing at random — it marks a specific, lower-earning-but-still-working population that a careless drop-the-NAs approach would silently discard rather than characterize.</p>
<section id="analysis-approach-next-phase" class="level2">
<h2 class="anchored" data-anchor-id="analysis-approach-next-phase">Analysis Approach (Next Phase)</h2>
<p>A natural next step is a classification model predicting the <code>&gt;50K</code> label, using this EDA’s findings to inform feature handling — treating <code>capital_gain</code>’s topcode as a flag rather than a literal value, deciding how to encode <code>workclass</code>’s structural missingness (its own category, most likely, given the analysis above), and choosing whether <code>fnlwgt</code> is used at all given its role as a sampling weight rather than a predictor. That modeling work, and its own results reporting, is out of scope for this document.</p>
</section>
</section>
<section id="technical-notes" class="level1">
<h1>Technical Notes</h1>
<section id="reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="reproducibility">Reproducibility</h2>
<ul>
<li>Environment: R 4.6.1, packages pinned in <code>renv.lock</code> (<code>renv::restore()</code> to match). Report rendered with the Quarto CLI bundled inside RStudio (<code>RStudio.app/Contents/Resources/app/quarto/bin/quarto</code>) — no standalone Quarto install required.</li>
<li>To reproduce: run <code>R/01_data_quality.R</code>, <code>R/02_general_eda.R</code>, <code>R/03_targeted_followups.R</code>, <code>R/04_wife_anomaly.R</code>, <code>R/06_quality_tables.R</code>, then <code>R/05_charts.R</code> (in that order — the later scripts depend on <code>data/processed/adult_clean.parquet</code> from the first) to regenerate everything in <code>data/processed/</code>, then render this file. Run <code>R/07_export_deliverables.R</code> afterward to refresh the standalone exports in <code>reports/figures/</code> and <code>reports/tables/</code>.</li>
</ul>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ol type="1">
<li>U.S. Census Bureau. <em>Income, Poverty, and Valuation of Noncash Benefits: 1994</em>. Current Population Reports, Series P60-189, April 1996. https://www.census.gov/library/publications/1996/demo/p60-189.html — median household income, 1994.</li>
<li>U.S. Census Bureau. Historical Income Tables: Households, Table H-1, “Income Limits for Each Fifth and Top 5 Percent of All Households.” https://www.census.gov/data/tables/time-series/demo/income-poverty/historical-income-households.html — 1994 household income quintile breakpoints.</li>
<li>U.S. Census Bureau. Historical Income Tables: People, Table P-38, “Full-Time, Year-Round All Workers by Median Earnings and Sex.” https://www.census.gov/data/tables/time-series/demo/income-poverty/historical-income-people.html — 1994 median individual annual earnings by sex.</li>
<li>U.S. Census Bureau. Historical Income Tables: Households, Table H-5, “Race and Hispanic Origin of Householder — Households by Median and Mean Income.” https://www.census.gov/data/tables/time-series/demo/income-poverty/historical-income-households.html — 1994 household median income by race.</li>
<li>U.S. Census Bureau. <em>The Relationship Between the 1990 Census and Census 2000 Industry and Occupation Classification Systems</em>, Technical Paper 65, 2003, Table 7. https://www.census.gov/library/publications/2003/demo/tp-65.html — 1990 Census 13-major-group occupation classification.</li>
<li>U.S. Census Bureau. Current Population Survey Technical Documentation, “Weighting.” https://www.census.gov/programs-surveys/cps/technical-documentation/methodology/weighting.html — independent confirmation of CPS final-weight (<code>fnlwgt</code>) methodology.</li>
</ol>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>